DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS user_data(
user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar(300) NOT NULL UNIQUE,
login varchar(300) NOT NULL UNIQUE,
name VARCHAR(300),
birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS film_data(
film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(300) NOT NULL UNIQUE,
description varchar(200)  DEFAULT 'не указано',
release_date DATE NOT NULL,
duration INTEGER NOT NULL,
rate long,
mpa_id long
);

CREATE TABLE IF NOT EXISTS friend(
user_id int,
friend_id int,
PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS mpa(
mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
mpa_name varchar(300) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_audience(
user_id INTEGER,
film_id INTEGER,
PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS film_genre(
film_id INTEGER,
genre_id INTEGER,
PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS genre(
genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
genre_name varchar(300) NOT NULL UNIQUE
);

ALTER TABLE film_data ADD FOREIGN KEY (mpa_id) REFERENCES mpa(mpa_id) ON DELETE SET NULL;

ALTER TABLE friend ADD FOREIGN KEY (user_id) REFERENCES user_data(user_id) ON DELETE CASCADE;
ALTER TABLE friend ADD FOREIGN KEY (friend_id) REFERENCES user_data(user_id) ON DELETE CASCADE;

ALTER TABLE film_audience ADD FOREIGN KEY (user_id) REFERENCES user_data(user_id) ON DELETE CASCADE;
ALTER TABLE film_audience ADD FOREIGN KEY (film_id) REFERENCES film_data(film_id) ON DELETE CASCADE;

ALTER TABLE film_genre ADD FOREIGN KEY (film_id) REFERENCES film_data(film_id) ON DELETE CASCADE;
ALTER TABLE film_genre ADD FOREIGN KEY (genre_id) REFERENCES genre(genre_id) ON DELETE CASCADE;